project_name: serve

before:
  hooks:
  - go mod download
  - go generate ./...

builds:
- # Builds linux, macos and windows executables
  main: ./cmd/serve/main.go
  env:
  - GOPROXY=https://proxy.golang.org
  binary: serve
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
    - arm
    - 386
  ignore:
    - goos: darwin
      goarch: 386
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X main.version={{.Version}}

brews:
  - github:
      owner: syntaqx
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/syntaqx/serve
    description: CLI to serve a static HTTP server anywhere you need one
    test: |
      system "#{bin}/serve", "version"

dockers:
  - goos: linux
    goarch: amd64
    ids: ["serve"]
    image_templates:
    - "syntaqx/serve:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    - "syntaqx/serve:{{ .Major }}.{{ .Minor }}"
    - "syntaqx/serve:{{ .Major }}"
    - "syntaqx/serve:latest"
    dockerfile: Dockerfile

archives:
  - id: tarball
    format: tar.gz
    replacements:
      darwin: macos
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
