language: go

go:
  - 1.13.x

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin latest
  - golangci-lint --version

install:
  - go mod download

script:
  - go mod tidy -v
  - go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...
  - golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true

notifications:
  email: false
